# Generated by Django 4.1 on 2022-09-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_roleproject_project_alter_project_members'),
        ('type_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeus',
            name='project',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
