# Generated by Django 4.1 on 2022-09-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='success', max_length=50),
            preserve_default=False,
        ),
    ]
