# Generated by Django 4.1 on 2022-09-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancellation_reason',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
