# Generated by Django 4.1 on 2022-09-25 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_permissionsproj_roleproject_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
