# Generated by Django 4.1.2 on 2022-11-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import user_story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('type_us', '0001_initial'),
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('business_value', models.IntegerField()),
                ('technical_priority', models.IntegerField()),
                ('estimation_time', models.IntegerField()),
                ('final_priority', models.IntegerField(null=True)),
                ('old_estimation_time', models.IntegerField(default=0)),
                ('previous_work', models.IntegerField(default=0)),
                ('work_hours', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('current_status', models.CharField(default='pending', max_length=20)),
                ('kanban_status', models.CharField(max_length=20, null=True)),
                ('cancellation_reason', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprintmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint')),
                ('us_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_us.typeus')),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=100)),
                ('work_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_story.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=user_story.models.us_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_story.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUserStory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('business_value', models.IntegerField()),
                ('technical_priority', models.IntegerField()),
                ('estimation_time', models.IntegerField()),
                ('final_priority', models.IntegerField(null=True)),
                ('old_estimation_time', models.IntegerField(default=0)),
                ('previous_work', models.IntegerField(default=0)),
                ('work_hours', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('current_status', models.CharField(default='pending', max_length=20)),
                ('kanban_status', models.CharField(max_length=20, null=True)),
                ('cancellation_reason', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sprints.sprintmember')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sprints.sprint')),
                ('us_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='type_us.typeus')),
            ],
            options={
                'verbose_name': 'historical user story',
                'verbose_name_plural': 'historical user storys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
