# Generated by Django 4.1 on 2022-09-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_roleproject_project_alter_project_members'),
        ('user_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember'),
        ),
    ]
