# Generated by Django 4.1.2 on 2022-11-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sprint_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
                ('capacity', models.IntegerField(default=0, null=True, verbose_name='Capacidad en horas')),
                ('available_capacity', models.IntegerField(null=True, verbose_name='Capacidad en horas restantes')),
                ('duration', models.IntegerField(verbose_name='Duración en días')),
                ('start_at', models.DateField(null=True, verbose_name='Fecha de inicio')),
                ('end_at', models.DateField(null=True, verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('finished', 'finished'), ('canceled', 'canceled'), ('in execution', 'in execution')], default='pending', max_length=20, verbose_name='Estado')),
                ('cancellation_reason', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprintMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='members',
            field=models.ManyToManyField(through='sprints.SprintMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
