# Generated by Django 4.1.1 on 2022-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_project",
            field=models.CharField(default="develop", max_length=50),
        ),
    ]
