# Generated by Django 4.1.1 on 2022-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_sys",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin"), ("visitor", "visitor")],
                default="visitor",
                max_length=7,
            ),
        ),
    ]
