# Generated by Django 4.1.1 on 2022-09-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type_role',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
