# Generated by Django 4.1.1 on 2022-09-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_roles', '0003_alter_role_options_alter_role_role_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('list_role', 'Can list role'), ('asing_role', 'Can asing role'))},
        ),
    ]
