# Generated by Django 4.1.1 on 2022-09-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_roles', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('list_role', 'Can list role'),)},
        ),
    ]
